//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace WorkReportService.WorkReport {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkReportBuildingEntity", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model", IsReference=true)]
    public partial class WorkReportBuildingEntity : WorkReportService.WorkReport.BaseEntity {
        
        private string BuildAuidField;
        
        private string BuildingNameField;
        
        private System.Nullable<decimal> BuildingTypeField;
        
        private string BuildingUseField;
        
        private System.Nullable<decimal> IdField;
        
        private System.Nullable<decimal> ResultField;
        
        private System.Nullable<decimal> SGroupIdField;
        
        private System.Nullable<decimal> WorkIdField;
        
        private System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportFloorEntity> WorkReportFloorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildAuid {
            get {
                return this.BuildAuidField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildAuidField, value) != true)) {
                    this.BuildAuidField = value;
                    this.RaisePropertyChanged("BuildAuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BuildingType {
            get {
                return this.BuildingTypeField;
            }
            set {
                if ((this.BuildingTypeField.Equals(value) != true)) {
                    this.BuildingTypeField = value;
                    this.RaisePropertyChanged("BuildingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingUse {
            get {
                return this.BuildingUseField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingUseField, value) != true)) {
                    this.BuildingUseField = value;
                    this.RaisePropertyChanged("BuildingUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SGroupId {
            get {
                return this.SGroupIdField;
            }
            set {
                if ((this.SGroupIdField.Equals(value) != true)) {
                    this.SGroupIdField = value;
                    this.RaisePropertyChanged("SGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportFloorEntity> WorkReportFloors {
            get {
                return this.WorkReportFloorsField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkReportFloorsField, value) != true)) {
                    this.WorkReportFloorsField = value;
                    this.RaisePropertyChanged("WorkReportFloors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveRecordHooksBase", Namespace="http://schemas.datacontract.org/2004/07/Castle.ActiveRecord", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.ActiveRecordBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.ActiveRecordValidationBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportFloorEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportLogEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkDetailInfoEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportBuildingEntity))]
    public partial class ActiveRecordHooksBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveRecordBase", Namespace="http://schemas.datacontract.org/2004/07/Castle.ActiveRecord", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.ActiveRecordValidationBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportFloorEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportLogEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkDetailInfoEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportBuildingEntity))]
    public partial class ActiveRecordBase : WorkReportService.WorkReport.ActiveRecordHooksBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveRecordValidationBase", Namespace="http://schemas.datacontract.org/2004/07/Castle.ActiveRecord", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportFloorEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportLogEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkDetailInfoEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportBuildingEntity))]
    public partial class ActiveRecordValidationBase : WorkReportService.WorkReport.ActiveRecordBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Wpms.App.Core.Framework.Entity", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportFloorEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportLogEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkDetailInfoEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkReportService.WorkReport.WorkReportBuildingEntity))]
    public partial class BaseEntity : WorkReportService.WorkReport.ActiveRecordValidationBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkReportFloorEntity", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model", IsReference=true)]
    public partial class WorkReportFloorEntity : WorkReportService.WorkReport.BaseEntity {
        
        private string FloorsCodeField;
        
        private string FloorsNameField;
        
        private string FloorsTypeField;
        
        private System.Nullable<decimal> IdField;
        
        private System.Nullable<decimal> ResultField;
        
        private System.Nullable<decimal> SGroupIdField;
        
        private System.Nullable<decimal> WorkIdField;
        
        private System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportLogEntity> WorkReportLogsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorsCode {
            get {
                return this.FloorsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorsCodeField, value) != true)) {
                    this.FloorsCodeField = value;
                    this.RaisePropertyChanged("FloorsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorsName {
            get {
                return this.FloorsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorsNameField, value) != true)) {
                    this.FloorsNameField = value;
                    this.RaisePropertyChanged("FloorsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorsType {
            get {
                return this.FloorsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorsTypeField, value) != true)) {
                    this.FloorsTypeField = value;
                    this.RaisePropertyChanged("FloorsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SGroupId {
            get {
                return this.SGroupIdField;
            }
            set {
                if ((this.SGroupIdField.Equals(value) != true)) {
                    this.SGroupIdField = value;
                    this.RaisePropertyChanged("SGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportLogEntity> WorkReportLogs {
            get {
                return this.WorkReportLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkReportLogsField, value) != true)) {
                    this.WorkReportLogsField = value;
                    this.RaisePropertyChanged("WorkReportLogs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkReportLogEntity", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model", IsReference=true)]
    public partial class WorkReportLogEntity : WorkReportService.WorkReport.BaseEntity {
        
        private string FloorAuidField;
        
        private System.Nullable<decimal> IdField;
        
        private System.Nullable<decimal> LogIdField;
        
        private string LogNameField;
        
        private string LogServertypeField;
        
        private System.Nullable<decimal> ResultField;
        
        private System.Nullable<decimal> SGroupIdField;
        
        private System.Nullable<decimal> WorkIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorAuid {
            get {
                return this.FloorAuidField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorAuidField, value) != true)) {
                    this.FloorAuidField = value;
                    this.RaisePropertyChanged("FloorAuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogName {
            get {
                return this.LogNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LogNameField, value) != true)) {
                    this.LogNameField = value;
                    this.RaisePropertyChanged("LogName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogServertype {
            get {
                return this.LogServertypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LogServertypeField, value) != true)) {
                    this.LogServertypeField = value;
                    this.RaisePropertyChanged("LogServertype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SGroupId {
            get {
                return this.SGroupIdField;
            }
            set {
                if ((this.SGroupIdField.Equals(value) != true)) {
                    this.SGroupIdField = value;
                    this.RaisePropertyChanged("SGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkDetailInfoEntity", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model", IsReference=true)]
    public partial class WorkDetailInfoEntity : WorkReportService.WorkReport.BaseEntity {
        
        private System.Nullable<decimal> ActEtimeField;
        
        private System.Nullable<decimal> ActStimeField;
        
        private string AddressField;
        
        private System.Nullable<decimal> AdminRegionField;
        
        private System.Nullable<decimal> AreaIdField;
        
        private System.Nullable<decimal> BuildingSumField;
        
        private System.Nullable<decimal> CityIdField;
        
        private System.Nullable<decimal> CompIdField;
        
        private string CompNameField;
        
        private System.Nullable<decimal> CreateTimeField;
        
        private string CreateUserNameField;
        
        private string CreateUseridField;
        
        private System.Nullable<System.DateTime> DbcreatetimeField;
        
        private string DelayReasonField;
        
        private System.Nullable<decimal> DendTimeField;
        
        private System.Nullable<decimal> DstartTimeField;
        
        private string FactoryField;
        
        private System.Nullable<decimal> GpsDistanceField;
        
        private System.Nullable<decimal> IsDelayField;
        
        private System.Nullable<decimal> IsNewBuildingField;
        
        private System.Nullable<decimal> IsautocreateField;
        
        private System.Nullable<decimal> IscompleteField;
        
        private System.Nullable<decimal> IsnottestedField;
        
        private System.Nullable<decimal> IsrecivedField;
        
        private System.Nullable<decimal> KmSumField;
        
        private System.Nullable<decimal> LevelValField;
        
        private string ManualIdField;
        
        private System.Nullable<decimal> NetTypeField;
        
        private string NewBuildingNameField;
        
        private System.Nullable<decimal> NoauditcompleteField;
        
        private System.Nullable<decimal> PlanEtimeField;
        
        private System.Nullable<decimal> PlanStimeField;
        
        private System.Nullable<decimal> ProblemtypeField;
        
        private System.Nullable<decimal> ProvinceIdField;
        
        private string RemarkField;
        
        private string SenderEmailField;
        
        private string SenderTelField;
        
        private string SenderUserNameField;
        
        private string SenderUseridField;
        
        private System.Nullable<decimal> SiteSumField;
        
        private string TestBuildingField;
        
        private string TestSiteField;
        
        private System.Nullable<decimal> TestTimeField;
        
        private string TesterEmailField;
        
        private string TesterTelField;
        
        private string TesterUserNameField;
        
        private string TesterUseridField;
        
        private System.Nullable<decimal> WorkAreaField;
        
        private System.Nullable<decimal> WorkIdField;
        
        private string WorkNameField;
        
        private System.Nullable<decimal> WorkStateField;
        
        private System.Nullable<decimal> WorkTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ActEtime {
            get {
                return this.ActEtimeField;
            }
            set {
                if ((this.ActEtimeField.Equals(value) != true)) {
                    this.ActEtimeField = value;
                    this.RaisePropertyChanged("ActEtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ActStime {
            get {
                return this.ActStimeField;
            }
            set {
                if ((this.ActStimeField.Equals(value) != true)) {
                    this.ActStimeField = value;
                    this.RaisePropertyChanged("ActStime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AdminRegion {
            get {
                return this.AdminRegionField;
            }
            set {
                if ((this.AdminRegionField.Equals(value) != true)) {
                    this.AdminRegionField = value;
                    this.RaisePropertyChanged("AdminRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AreaId {
            get {
                return this.AreaIdField;
            }
            set {
                if ((this.AreaIdField.Equals(value) != true)) {
                    this.AreaIdField = value;
                    this.RaisePropertyChanged("AreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BuildingSum {
            get {
                return this.BuildingSumField;
            }
            set {
                if ((this.BuildingSumField.Equals(value) != true)) {
                    this.BuildingSumField = value;
                    this.RaisePropertyChanged("BuildingSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CompId {
            get {
                return this.CompIdField;
            }
            set {
                if ((this.CompIdField.Equals(value) != true)) {
                    this.CompIdField = value;
                    this.RaisePropertyChanged("CompId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompName {
            get {
                return this.CompNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompNameField, value) != true)) {
                    this.CompNameField = value;
                    this.RaisePropertyChanged("CompName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserid {
            get {
                return this.CreateUseridField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUseridField, value) != true)) {
                    this.CreateUseridField = value;
                    this.RaisePropertyChanged("CreateUserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dbcreatetime {
            get {
                return this.DbcreatetimeField;
            }
            set {
                if ((this.DbcreatetimeField.Equals(value) != true)) {
                    this.DbcreatetimeField = value;
                    this.RaisePropertyChanged("Dbcreatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelayReason {
            get {
                return this.DelayReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.DelayReasonField, value) != true)) {
                    this.DelayReasonField = value;
                    this.RaisePropertyChanged("DelayReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DendTime {
            get {
                return this.DendTimeField;
            }
            set {
                if ((this.DendTimeField.Equals(value) != true)) {
                    this.DendTimeField = value;
                    this.RaisePropertyChanged("DendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DstartTime {
            get {
                return this.DstartTimeField;
            }
            set {
                if ((this.DstartTimeField.Equals(value) != true)) {
                    this.DstartTimeField = value;
                    this.RaisePropertyChanged("DstartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factory {
            get {
                return this.FactoryField;
            }
            set {
                if ((object.ReferenceEquals(this.FactoryField, value) != true)) {
                    this.FactoryField = value;
                    this.RaisePropertyChanged("Factory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> GpsDistance {
            get {
                return this.GpsDistanceField;
            }
            set {
                if ((this.GpsDistanceField.Equals(value) != true)) {
                    this.GpsDistanceField = value;
                    this.RaisePropertyChanged("GpsDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IsDelay {
            get {
                return this.IsDelayField;
            }
            set {
                if ((this.IsDelayField.Equals(value) != true)) {
                    this.IsDelayField = value;
                    this.RaisePropertyChanged("IsDelay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IsNewBuilding {
            get {
                return this.IsNewBuildingField;
            }
            set {
                if ((this.IsNewBuildingField.Equals(value) != true)) {
                    this.IsNewBuildingField = value;
                    this.RaisePropertyChanged("IsNewBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Isautocreate {
            get {
                return this.IsautocreateField;
            }
            set {
                if ((this.IsautocreateField.Equals(value) != true)) {
                    this.IsautocreateField = value;
                    this.RaisePropertyChanged("Isautocreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Iscomplete {
            get {
                return this.IscompleteField;
            }
            set {
                if ((this.IscompleteField.Equals(value) != true)) {
                    this.IscompleteField = value;
                    this.RaisePropertyChanged("Iscomplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Isnottested {
            get {
                return this.IsnottestedField;
            }
            set {
                if ((this.IsnottestedField.Equals(value) != true)) {
                    this.IsnottestedField = value;
                    this.RaisePropertyChanged("Isnottested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Isrecived {
            get {
                return this.IsrecivedField;
            }
            set {
                if ((this.IsrecivedField.Equals(value) != true)) {
                    this.IsrecivedField = value;
                    this.RaisePropertyChanged("Isrecived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> KmSum {
            get {
                return this.KmSumField;
            }
            set {
                if ((this.KmSumField.Equals(value) != true)) {
                    this.KmSumField = value;
                    this.RaisePropertyChanged("KmSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LevelVal {
            get {
                return this.LevelValField;
            }
            set {
                if ((this.LevelValField.Equals(value) != true)) {
                    this.LevelValField = value;
                    this.RaisePropertyChanged("LevelVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManualId {
            get {
                return this.ManualIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ManualIdField, value) != true)) {
                    this.ManualIdField = value;
                    this.RaisePropertyChanged("ManualId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NetType {
            get {
                return this.NetTypeField;
            }
            set {
                if ((this.NetTypeField.Equals(value) != true)) {
                    this.NetTypeField = value;
                    this.RaisePropertyChanged("NetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewBuildingName {
            get {
                return this.NewBuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewBuildingNameField, value) != true)) {
                    this.NewBuildingNameField = value;
                    this.RaisePropertyChanged("NewBuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Noauditcomplete {
            get {
                return this.NoauditcompleteField;
            }
            set {
                if ((this.NoauditcompleteField.Equals(value) != true)) {
                    this.NoauditcompleteField = value;
                    this.RaisePropertyChanged("Noauditcomplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PlanEtime {
            get {
                return this.PlanEtimeField;
            }
            set {
                if ((this.PlanEtimeField.Equals(value) != true)) {
                    this.PlanEtimeField = value;
                    this.RaisePropertyChanged("PlanEtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PlanStime {
            get {
                return this.PlanStimeField;
            }
            set {
                if ((this.PlanStimeField.Equals(value) != true)) {
                    this.PlanStimeField = value;
                    this.RaisePropertyChanged("PlanStime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Problemtype {
            get {
                return this.ProblemtypeField;
            }
            set {
                if ((this.ProblemtypeField.Equals(value) != true)) {
                    this.ProblemtypeField = value;
                    this.RaisePropertyChanged("Problemtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmail {
            get {
                return this.SenderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailField, value) != true)) {
                    this.SenderEmailField = value;
                    this.RaisePropertyChanged("SenderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderTel {
            get {
                return this.SenderTelField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderTelField, value) != true)) {
                    this.SenderTelField = value;
                    this.RaisePropertyChanged("SenderTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUserName {
            get {
                return this.SenderUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUserNameField, value) != true)) {
                    this.SenderUserNameField = value;
                    this.RaisePropertyChanged("SenderUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUserid {
            get {
                return this.SenderUseridField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUseridField, value) != true)) {
                    this.SenderUseridField = value;
                    this.RaisePropertyChanged("SenderUserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SiteSum {
            get {
                return this.SiteSumField;
            }
            set {
                if ((this.SiteSumField.Equals(value) != true)) {
                    this.SiteSumField = value;
                    this.RaisePropertyChanged("SiteSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestBuilding {
            get {
                return this.TestBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.TestBuildingField, value) != true)) {
                    this.TestBuildingField = value;
                    this.RaisePropertyChanged("TestBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestSite {
            get {
                return this.TestSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.TestSiteField, value) != true)) {
                    this.TestSiteField = value;
                    this.RaisePropertyChanged("TestSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TestTime {
            get {
                return this.TestTimeField;
            }
            set {
                if ((this.TestTimeField.Equals(value) != true)) {
                    this.TestTimeField = value;
                    this.RaisePropertyChanged("TestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TesterEmail {
            get {
                return this.TesterEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.TesterEmailField, value) != true)) {
                    this.TesterEmailField = value;
                    this.RaisePropertyChanged("TesterEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TesterTel {
            get {
                return this.TesterTelField;
            }
            set {
                if ((object.ReferenceEquals(this.TesterTelField, value) != true)) {
                    this.TesterTelField = value;
                    this.RaisePropertyChanged("TesterTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TesterUserName {
            get {
                return this.TesterUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TesterUserNameField, value) != true)) {
                    this.TesterUserNameField = value;
                    this.RaisePropertyChanged("TesterUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TesterUserid {
            get {
                return this.TesterUseridField;
            }
            set {
                if ((object.ReferenceEquals(this.TesterUseridField, value) != true)) {
                    this.TesterUseridField = value;
                    this.RaisePropertyChanged("TesterUserid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkArea {
            get {
                return this.WorkAreaField;
            }
            set {
                if ((this.WorkAreaField.Equals(value) != true)) {
                    this.WorkAreaField = value;
                    this.RaisePropertyChanged("WorkArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkId {
            get {
                return this.WorkIdField;
            }
            set {
                if ((this.WorkIdField.Equals(value) != true)) {
                    this.WorkIdField = value;
                    this.RaisePropertyChanged("WorkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkName {
            get {
                return this.WorkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkNameField, value) != true)) {
                    this.WorkNameField = value;
                    this.RaisePropertyChanged("WorkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkState {
            get {
                return this.WorkStateField;
            }
            set {
                if ((this.WorkStateField.Equals(value) != true)) {
                    this.WorkStateField = value;
                    this.RaisePropertyChanged("WorkState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WorkType {
            get {
                return this.WorkTypeField;
            }
            set {
                if ((this.WorkTypeField.Equals(value) != true)) {
                    this.WorkTypeField = value;
                    this.RaisePropertyChanged("WorkType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderClause", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model")]
    public partial class OrderClause : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysDictionary", Namespace="http://schemas.datacontract.org/2004/07/WorkQualityReport.Model")]
    public partial class SysDictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CnNameField;
        
        private string EnNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CnName {
            get {
                return this.CnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CnNameField, value) != true)) {
                    this.CnNameField = value;
                    this.RaisePropertyChanged("CnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName {
            get {
                return this.EnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnNameField, value) != true)) {
                    this.EnNameField = value;
                    this.RaisePropertyChanged("EnName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkReport.IQualityReport")]
    public interface IQualityReport {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQualityReport/GetWorkReport", ReplyAction="http://tempuri.org/IQualityReport/GetWorkReportResponse")]
        System.IAsyncResult BeginGetWorkReport(int workId, int subGroupId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> EndGetWorkReport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQualityReport/GetAllWorkOrder", ReplyAction="http://tempuri.org/IQualityReport/GetAllWorkOrderResponse")]
        System.IAsyncResult BeginGetAllWorkOrder(WorkReportService.WorkReport.OrderClause clause, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> EndGetAllWorkOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IQualityReport/QueryDict", ReplyAction="http://tempuri.org/IQualityReport/QueryDictResponse")]
        System.IAsyncResult BeginQueryDict(string value, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> EndQueryDict(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQualityReportChannel : WorkReportService.WorkReport.IQualityReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QualityReportClient : System.ServiceModel.ClientBase<WorkReportService.WorkReport.IQualityReport>, WorkReportService.WorkReport.IQualityReport {
        
        private BeginOperationDelegate onBeginGetWorkReportDelegate;
        
        private EndOperationDelegate onEndGetWorkReportDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkReportCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllWorkOrderDelegate;
        
        private EndOperationDelegate onEndGetAllWorkOrderDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllWorkOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryDictDelegate;
        
        private EndOperationDelegate onEndQueryDictDelegate;
        
        private System.Threading.SendOrPostCallback onQueryDictCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public QualityReportClient() {
        }
        
        public QualityReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QualityReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetWorkReportCompletedEventArgs> GetWorkReportCompleted;
        
        public event System.EventHandler<GetAllWorkOrderCompletedEventArgs> GetAllWorkOrderCompleted;
        
        public event System.EventHandler<QueryDictCompletedEventArgs> QueryDictCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorkReportService.WorkReport.IQualityReport.BeginGetWorkReport(int workId, int subGroupId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkReport(workId, subGroupId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> WorkReportService.WorkReport.IQualityReport.EndGetWorkReport(System.IAsyncResult result) {
            return base.Channel.EndGetWorkReport(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkReport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int workId = ((int)(inValues[0]));
            int subGroupId = ((int)(inValues[1]));
            return ((WorkReportService.WorkReport.IQualityReport)(this)).BeginGetWorkReport(workId, subGroupId, callback, asyncState);
        }
        
        private object[] OnEndGetWorkReport(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> retVal = ((WorkReportService.WorkReport.IQualityReport)(this)).EndGetWorkReport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkReportCompleted(object state) {
            if ((this.GetWorkReportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkReportCompleted(this, new GetWorkReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkReportAsync(int workId, int subGroupId) {
            this.GetWorkReportAsync(workId, subGroupId, null);
        }
        
        public void GetWorkReportAsync(int workId, int subGroupId, object userState) {
            if ((this.onBeginGetWorkReportDelegate == null)) {
                this.onBeginGetWorkReportDelegate = new BeginOperationDelegate(this.OnBeginGetWorkReport);
            }
            if ((this.onEndGetWorkReportDelegate == null)) {
                this.onEndGetWorkReportDelegate = new EndOperationDelegate(this.OnEndGetWorkReport);
            }
            if ((this.onGetWorkReportCompletedDelegate == null)) {
                this.onGetWorkReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkReportCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkReportDelegate, new object[] {
                        workId,
                        subGroupId}, this.onEndGetWorkReportDelegate, this.onGetWorkReportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorkReportService.WorkReport.IQualityReport.BeginGetAllWorkOrder(WorkReportService.WorkReport.OrderClause clause, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllWorkOrder(clause, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> WorkReportService.WorkReport.IQualityReport.EndGetAllWorkOrder(System.IAsyncResult result) {
            return base.Channel.EndGetAllWorkOrder(result);
        }
        
        private System.IAsyncResult OnBeginGetAllWorkOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WorkReportService.WorkReport.OrderClause clause = ((WorkReportService.WorkReport.OrderClause)(inValues[0]));
            return ((WorkReportService.WorkReport.IQualityReport)(this)).BeginGetAllWorkOrder(clause, callback, asyncState);
        }
        
        private object[] OnEndGetAllWorkOrder(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> retVal = ((WorkReportService.WorkReport.IQualityReport)(this)).EndGetAllWorkOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllWorkOrderCompleted(object state) {
            if ((this.GetAllWorkOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllWorkOrderCompleted(this, new GetAllWorkOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllWorkOrderAsync(WorkReportService.WorkReport.OrderClause clause) {
            this.GetAllWorkOrderAsync(clause, null);
        }
        
        public void GetAllWorkOrderAsync(WorkReportService.WorkReport.OrderClause clause, object userState) {
            if ((this.onBeginGetAllWorkOrderDelegate == null)) {
                this.onBeginGetAllWorkOrderDelegate = new BeginOperationDelegate(this.OnBeginGetAllWorkOrder);
            }
            if ((this.onEndGetAllWorkOrderDelegate == null)) {
                this.onEndGetAllWorkOrderDelegate = new EndOperationDelegate(this.OnEndGetAllWorkOrder);
            }
            if ((this.onGetAllWorkOrderCompletedDelegate == null)) {
                this.onGetAllWorkOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllWorkOrderCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllWorkOrderDelegate, new object[] {
                        clause}, this.onEndGetAllWorkOrderDelegate, this.onGetAllWorkOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorkReportService.WorkReport.IQualityReport.BeginQueryDict(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryDict(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> WorkReportService.WorkReport.IQualityReport.EndQueryDict(System.IAsyncResult result) {
            return base.Channel.EndQueryDict(result);
        }
        
        private System.IAsyncResult OnBeginQueryDict(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return ((WorkReportService.WorkReport.IQualityReport)(this)).BeginQueryDict(value, callback, asyncState);
        }
        
        private object[] OnEndQueryDict(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> retVal = ((WorkReportService.WorkReport.IQualityReport)(this)).EndQueryDict(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryDictCompleted(object state) {
            if ((this.QueryDictCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryDictCompleted(this, new QueryDictCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryDictAsync(string value) {
            this.QueryDictAsync(value, null);
        }
        
        public void QueryDictAsync(string value, object userState) {
            if ((this.onBeginQueryDictDelegate == null)) {
                this.onBeginQueryDictDelegate = new BeginOperationDelegate(this.OnBeginQueryDict);
            }
            if ((this.onEndQueryDictDelegate == null)) {
                this.onEndQueryDictDelegate = new EndOperationDelegate(this.OnEndQueryDict);
            }
            if ((this.onQueryDictCompletedDelegate == null)) {
                this.onQueryDictCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryDictCompleted);
            }
            base.InvokeAsync(this.onBeginQueryDictDelegate, new object[] {
                        value}, this.onEndQueryDictDelegate, this.onQueryDictCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WorkReportService.WorkReport.IQualityReport CreateChannel() {
            return new QualityReportClientChannel(this);
        }
        
        private class QualityReportClientChannel : ChannelBase<WorkReportService.WorkReport.IQualityReport>, WorkReportService.WorkReport.IQualityReport {
            
            public QualityReportClientChannel(System.ServiceModel.ClientBase<WorkReportService.WorkReport.IQualityReport> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetWorkReport(int workId, int subGroupId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = workId;
                _args[1] = subGroupId;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkReport", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> EndGetWorkReport(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity> _result = ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkReportBuildingEntity>)(base.EndInvoke("GetWorkReport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllWorkOrder(WorkReportService.WorkReport.OrderClause clause, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = clause;
                System.IAsyncResult _result = base.BeginInvoke("GetAllWorkOrder", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> EndGetAllWorkOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity> _result = ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.WorkDetailInfoEntity>)(base.EndInvoke("GetAllWorkOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQueryDict(string value, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("QueryDict", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> EndQueryDict(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary> _result = ((System.Collections.ObjectModel.ObservableCollection<WorkReportService.WorkReport.SysDictionary>)(base.EndInvoke("QueryDict", _args, result)));
                return _result;
            }
        }
    }
}
